services:
  app:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - REDIS_URL=redis://cache:6378
      - PORT=4000
    depends_on:
      - cache

  cache:
    image: redis:7-alpine
    ports:
      - "6378:6378"
    restart: always